apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: ${{values.description}}
  annotations:
    backstage.io/kubernetes-id: ${{values.name}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    argocd/app-name: ${{values.name}}
    argocd/app-namespace: openshift-gitops
    tektonci/build-namespace: ${{values.namespace}}
  tags:
    - frontend
    - html
    - neuralbank
spec:
  type: website
  lifecycle: experimental
  owner: user:${{values.owner}}
  system: neuralbank
  consumesApis:
    - neuralbank-backend-api
  dependsOn:
    - component:default/neuralbank-backend
