ProxyPreserveHost Off

ProxyPass "/api/backend/" "http://neuralbank-backend-gateway-istio:8080/api/" timeout=30 retry=5
ProxyPassReverse "/api/backend/" "http://neuralbank-backend-gateway-istio:8080/api/"

ProxyPass "/api/mcp/" "http://customer-service-mcp-gateway-istio:8080/" timeout=30 retry=5
ProxyPassReverse "/api/mcp/" "http://customer-service-mcp-gateway-istio:8080/"
