site_name: Platform Observability
site_description: Grafana, Prometheus y stack de observabilidad del cluster
nav:
  - Home: index.md
  - Acceso a Grafana: grafana.md
  - Arquitectura: architecture.md
  - Dashboards:
    - API Gateway Metrics: dashboards/api-gateway.md
    - Service Mesh Overview: dashboards/service-mesh.md
  - Consolas:
    - Kiali (Service Mesh): consoles/kiali.md
    - Thanos Querier: consoles/thanos.md
plugins:
  - techdocs-core
markdown_extensions:
  - attr_list
