apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ${{values.name}}-build
  namespace: ${{values.namespace}}
  labels:
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: main
    - name: image-name
      type: string
      default: "${{values.imageRegistry}}/${{values.namespace}}/${{values.name}}:latest"
  workspaces:
    - name: source
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      runAfter:
        - git-clone
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: $(params.image-name)
      workspaces:
        - name: source
          workspace: source
    - name: deploy
      runAfter:
        - build-image
      taskRef:
        name: openshift-client
        kind: ClusterTask
      params:
        - name: SCRIPT
          value: |
            oc rollout restart deployment/${{values.name}} -n ${{values.namespace}} || true
