apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ${{values.name}}
  namespace: ${{values.namespace}}
  labels:
    app.kubernetes.io/name: ${{values.name}}
    backstage.io/kubernetes-id: ${{values.name}}
spec:
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ${{values.name}}
    weight: 100
