quarkus.http.port=8080
quarkus.container-image.build=true
quarkus.container-image.push=true
quarkus.container-image.registry=${{values.imageRegistry}}
quarkus.container-image.group=${{values.namespace}}
quarkus.container-image.name=${{values.name}}
quarkus.container-image.tag=latest
