title: "From Zero To Hero with Red Hat Developer Hub"
description: "Workshop — Neuralbank on OpenShift — Red Hat Developer Hub"
baseurl: "/test-drive-pe-oscg"
url: "https://maximilianopizarro.github.io"
remote_theme: just-the-docs/just-the-docs@v0.10.0
color_scheme: custom
logo: "/assets/images/Logo-OSC_with_padding.png"

aux_links:
  "Red Hat Developers":
    - "https://developers.redhat.com"
  "GitHub":
    - "https://github.com/maximilianoPizarro/test-drive-pe-oscg"
aux_links_new_tab: true

footer_content: '<img src="/test-drive-pe-oscg/assets/images/Logo-OSC_with_padding.png" alt="OpenShift Commons Gathering" style="height:24px;vertical-align:middle;margin-right:6px;">OpenShift Commons Gathering — Buenos Aires 2026 · Created by <a href="https://maximilianopizarro.github.io/" target="_blank">Maximiliano Pizarro</a> · Powered by <a href="https://developers.redhat.com/rhdh" target="_blank">Red Hat Developer Hub</a>'

favicon_ico: "/test-drive-pe-oscg/assets/images/favicon.ico"

mermaid:
  version: "10.9.0"

enable_copy_code_button: true

plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
