apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous=true
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true
    argocd.argoproj.io/sync-wave: "7"
  labels:
    app.kubernetes.io/instance: devspaces
  name: devspaces
  namespace: devspaces
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    devWorkspace: {}
    devfileRegistry: {}
    imagePuller:
      enable: false
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  devEnvironments:
    startTimeoutSeconds: 600
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    secondsOfRunBeforeIdling: 1800
    storage:
      pvcStrategy: per-user
  gitServices: {}
  networking: {}
