apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: software-templates
  description: Software Templates for Developer Hub
spec:
  targets:
    - ./customer-service-mcp/template.yaml
    - ./neuralbank-backend/template.yaml
    - ./neuralbank-frontend/template.yaml
